services:
  schemaquench:
    build:
      context: .
      dockerfile: SchemaQuench/Dockerfile
    image: schemasmithyfree/schemaquench:${QUENCH_VERSION}
    
  update-testproduct:
    image: schemasmithyfree/schemaquench:${QUENCH_VERSION}
    environment:
      - QuenchSettings_Target__Server=db
      - QuenchSettings_Target__User=${MSSQL_SA_USERNAME}
      - QuenchSettings_Target__Password=${MSSQL_SA_PASSWORD}
      - QuenchSettings_SchemaPackagePath=/metadata
      - QuenchSettings_ScriptTokens__MainDB=TestMain
      - QuenchSettings_ScriptTokens__SecondaryDB=TestSecondary
      - QuenchSettings_ScriptTokens__ReleaseVersion=1.0.0
    volumes:
      - ./TestProducts/ValidProduct:/metadata
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./db
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "${MSSQL_PORT:-1440}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_USERNAME=${MSSQL_SA_USERNAME}    
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}    
    healthcheck:
      test: /tmp/devdatabase/is-ready.sh
      interval: 60s
      timeout: 3s
      retries: 10
      start_period: 60s

  completed:
    image: alpine
    entrypoint: ["echo"]
    command: ["completed"]
    depends_on:
      db:
        condition: service_healthy
      update-testproduct:
        condition: service_completed_successfully
