USE master
GO

PRINT 'Alter the sa login'
GO

ALTER LOGIN [sa] WITH NAME = [$(MSSQL_SA_USERNAME)]
GO

PRINT 'Alter the sa login (done)'
GO

DROP DATABASE IF EXISTS Northwind
GO
CREATE DATABASE Northwind
GO

DROP DATABASE IF EXISTS AdventureWorks
GO
CREATE DATABASE AdventureWorks
GO

DROP DATABASE IF EXISTS Registry
GO
CREATE DATABASE Registry
GO

DROP DATABASE IF EXISTS Client1
GO
CREATE DATABASE Client1
GO

DROP DATABASE IF EXISTS Client2
GO
CREATE DATABASE Client2
GO

ALTER DATABASE AdventureWorks
SET RECOVERY SIMPLE,
    ANSI_NULLS ON,
    ANSI_PADDING ON,
    ANSI_WARNINGS ON,
    ARITHABORT ON,
    CONCAT_NULL_YIELDS_NULL ON,
    QUOTED_IDENTIFIER ON,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    ALLOW_SNAPSHOT_ISOLATION OFF;
GO

PRINT 'Initialize databases done'
GO
-- Integration test databases
USE master
GO
DROP DATABASE IF EXISTS TestMain
GO
CREATE DATABASE TestMain
GO
USE TestMain
GO
CREATE SCHEMA SchemaSmith
CREATE TABLE SchemaSmith.TestLog (Id INT IDENTITY(1,1) NOT NULL, Msg VARCHAR(2000) NOT NULL)
GO

USE master
GO
DROP DATABASE IF EXISTS TestSecondary
GO
CREATE DATABASE TestSecondary
GO
USE TestSecondary
GO
CREATE SCHEMA SchemaSmith
CREATE TABLE SchemaSmith.TestLog (Id INT IDENTITY(1,1) NOT NULL, Msg VARCHAR(2000) NOT NULL)
GO
