DROP TABLE IF EXISTS DATABASECHANGELOG;
DROP TABLE IF EXISTS DATABASECHANGELOGLOCK;
CREATE TABLE DATABASECHANGELOGLOCK (
  ID          INT NOT NULL,
  LOCKED      TINYINT(1) NOT NULL,
  LOCKGRANTED DATETIME NULL,
  LOCKEDBY    VARCHAR(255) NULL,
  CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)
) ENGINE=InnoDB;
INSERT INTO DATABASECHANGELOGLOCK (ID,LOCKED) VALUES (1,0);
CREATE TABLE DATABASECHANGELOG (
  ID            VARCHAR(255) NOT NULL,
  AUTHOR        VARCHAR(255) NOT NULL,
  FILENAME      VARCHAR(255) NOT NULL,
  DATEEXECUTED  DATETIME NOT NULL,
  ORDEREXECUTED INT NOT NULL,
  EXECTYPE      VARCHAR(10) NOT NULL,
  MD5SUM        VARCHAR(35),
  DESCRIPTION   VARCHAR(255),
  COMMENTS      VARCHAR(255),
  TAG           VARCHAR(255),
  LIQUIBASE     VARCHAR(20),
  CONTEXTS      VARCHAR(255),
  LABELS        VARCHAR(255),
  DEPLOYMENT_ID VARCHAR(10)
) ENGINE=InnoDB;
INSERT INTO DATABASECHANGELOG (ID,AUTHOR,FILENAME,DATEEXECUTED,ORDEREXECUTED,EXECTYPE,DESCRIPTION)
VALUES ('1','dev','db.changelog-master.xml',NOW(),1,'EXECUTED','createTable shop'),
       ('2','dev','db.changelog-master.xml',NOW(),2,'EXECUTED','addForeignKeyConstraint');
