-- Copyright (c) SchemaSmith Contributors. Licensed under the SSCL v2.0.
-- Licensed for use and modification with SchemaSmith products only.
-- Redistribution outside of SchemaSmith product usage is prohibited.

-- The two-argument form must go explicitly: CREATE OR REPLACE with a new parameter creates an
-- OVERLOAD rather than replacing, and a two-argument call would then be ambiguous between the old
-- function and the new one's default -- an error, on a kindled database that used to work.
DROP FUNCTION IF EXISTS "SchemaSmith"."GenerateTableJSON"(varchar, varchar);

-- p_ObjectOrder: 'Name' (default, alphabetical) or 'Physical' (the table's own column order).
-- COLUMNS ONLY at this layer. It carries SchemaTongs' Product:ObjectOrder setting, which also orders
-- indexes, foreign keys and check constraints -- but the caller sequences those after this function
-- returns, not here.
CREATE OR REPLACE FUNCTION "SchemaSmith"."GenerateTableJSON"(p_Schema varchar(200), p_Table varchar(200), p_ObjectOrder varchar(20) DEFAULT 'Name')
  RETURNS text
  LANGUAGE plpgsql
AS $function$
DECLARE result_string TEXT;
BEGIN
SELECT "SchemaSmith"."FormatJson"(ROW_TO_JSON(tbl))
  INTO result_string
  FROM (SELECT t.table_schema AS "Schema",
               t.table_name AS "Name",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT c.column_name AS "Name",
                               -- An array column reports udt_name '_text' while the package declares 'text[]', so the composed
                               -- form was never equal to the declared one and the column was re-modified on every deploy --
                               -- for ANY PostgreSQL array column, not one type. format_type renders the canonical declared
                               -- spelling directly, including element typmods (character varying(20)[], numeric(10,2)[]).
                               CASE WHEN c.data_type = 'ARRAY' THEN REGEXP_REPLACE(c.udt_name, '^_', '') || COALESCE(SUBSTRING(format_type(a.atttypid, a.atttypmod) FROM '\(.*\)'), '') || '[]' ELSE
                               CASE WHEN c.domain_name IS NOT NULL
                                    THEN CASE WHEN c.domain_schema != 'pg_catalog' THEN '"' || c.domain_schema || '".' ELSE '' END || '"' || c.domain_name || '"'
                                    ELSE CASE WHEN c.udt_schema != 'pg_catalog' THEN c.udt_schema || '.' ELSE '' END || REGEXP_REPLACE(c.udt_name, 'bpchar', 'CHAR', 'i')
                                    END ||
                               "SchemaSmith"."ColumnTypeArguments"(c.domain_name, c.udt_name, c.character_maximum_length, c.numeric_precision, c.numeric_scale, c.datetime_precision) END AS "DataType",
                               CASE WHEN c.is_nullable = 'YES' THEN TRUE ELSE FALSE END AS "Nullable",
                               "SchemaSmith"."StripParenWrapping"(c.column_default) AS "Default",
                               c.collation_name AS "Collation",
                               CASE WHEN a.attidentity = 'd'
                                    THEN 'GENERATED BY DEFAULT AS IDENTITY'
                                    WHEN a.attidentity = 'a'
                                    THEN 'GENERATED ALWAYS AS IDENTITY' ||
                                         CASE WHEN s.seqstart IS NOT NULL
                                              THEN '(START WITH ' || s.seqstart || ' INCREMENT BY ' || s.seqincrement  || ')'
                                              ELSE ''
                                              END
                                    ELSE c.is_generated END AS "Generated",
                               c.generation_expression AS "GenerationExpression",
                               CASE WHEN a.attgenerated = '' OR a.attgenerated = 's' THEN FALSE ELSE TRUE END AS "Virtual",
                               CASE a.attstorage
                                   WHEN 'p' THEN 'PLAIN'
                                   WHEN 'm' THEN 'MAIN'
                                   WHEN 'e' THEN 'EXTERNAL'
                                   WHEN 'x' THEN 'EXTENDED'
                                   ELSE 'DEFAULT' END AS "Storage",
                               "SchemaSmith"."ColumnCompression"(a.attrelid, a.attnum) AS "Compression",
                               '' AS "ShouldApplyExpression",
                               '' AS "OldName"
                          FROM information_schema.columns c
                          JOIN pg_attribute a ON a.attrelid = ('"' || c.table_schema || '"."' || c.table_name || '"')::regclass
                                             AND a.attname = c.column_name
                                             AND NOT a.attisdropped
                          LEFT JOIN pg_depend d ON d.refclassid = 'pg_class'::regclass
                                               AND d.refobjid = a.attrelid
                                               AND d.refobjsubid = a.attnum
                                               AND d.classid = 'pg_class'::regclass
                                               AND d.deptype = 'i' -- Internal dependency, specifically for identity columns
                          LEFT JOIN pg_sequence s ON s.seqrelid = d.objid
                          WHERE t.table_schema = c.table_schema
                            AND t.table_name = c.table_name
                          -- Column sequence is a caller choice: 'Name' (default, and what the tool
                          -- writes) or 'Physical', the table's own order. Only the column list honours it --
                          -- indexes and constraints have no ordinal anyone authors toward.
                          ORDER BY CASE WHEN LOWER(p_ObjectOrder) = 'physical' THEN c.ordinal_position END,
                                   CASE WHEN LOWER(p_ObjectOrder) = 'physical' THEN NULL ELSE c.column_name END
                         ) sub) AS "Columns",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT i.relname AS "Name",
                               idx.indisprimary AS "PrimaryKey",
                               idx.indisunique AS "Unique",
                               CASE WHEN con.contype = 'u' THEN TRUE ELSE FALSE END AS "UniqueConstraint",
                               idx.indisclustered AS "Clustered",
                               (SELECT STRING_AGG(TRIM(BOTH '"' FROM PG_GET_INDEXDEF(idx.indexrelid, idx::int4, true)) ||
                                                  CASE WHEN (idx.indoption[idx-1] & 1) = 1 THEN ' DESC' || CASE WHEN (idx.indoption[idx-1] & 2) = 2 THEN '' ELSE ' NULLS LAST' END
                                                       ELSE CASE WHEN (idx.indoption[idx-1] & 2) = 2 THEN ' NULLS FIRST' ELSE '' END
                                                      END, ',' ORDER BY idx)
                                  FROM UNNEST(idx.indkey) WITH ORDINALITY AS u(element, idx)
                                  WHERE idx <= idx.indnkeyatts) AS "IndexColumns",
                               (SELECT STRING_AGG(a.attname, ',' ORDER BY idx)
                                  FROM pg_attribute a
                                  CROSS JOIN LATERAL UNNEST(idx.indkey) WITH ORDINALITY AS u(element, idx)
                                  WHERE a.attrelid = idx.indrelid
                                    AND idx > idx.indnkeyatts
                                    AND a.attnum = element) AS "IncludeColumns",
                               (SELECT am.amname FROM pg_am am WHERE i.relam = am.oid AND i.relkind = 'i') AS "AccessMethod",
                               "SchemaSmith"."StripParenWrapping"(PG_GET_EXPR(idx.indpred, idx.indrelid)) AS "FilterExpression",
                               '' AS "ShouldApplyExpression",
                               CASE WHEN 'fillfactor=100' = ANY(i.reloptions) THEN 100
                                    WHEN i.reloptions IS NULL THEN 90 -- Default for B-tree indexes
                                    ELSE (REGEXP_MATCH(ARRAY_TO_STRING(i.reloptions, ','), 'fillfactor=(\d+)') ) [1] ::int
                                    END AS "FillFactor",
                               "SchemaSmith"."IndexNullsNotDistinct"(idx.indexrelid) AS "NullsNotDistinct",
                               COALESCE(con.condeferrable, FALSE) AS "Deferrable",
                               COALESCE(con.condeferred, FALSE) AS "InitiallyDeferred",
                               -- reltablespace 0 means "the database default", which is NOT a declared
                               -- placement -- it yields NULL so FormatJson strips the key and an ordinary
                               -- index extracts exactly as it did before this shipped. An index does not
                               -- inherit its table's tablespace, so this is read per index.
                               (SELECT ts.spcname FROM pg_tablespace ts WHERE ts.oid = i.reltablespace) AS "Tablespace",
                               -- Storage parameters (the WITH clause) as an object, minus fillfactor which
                               -- FillFactor above owns. This is what carries a vector index's m /
                               -- ef_construction / lists. JSON_OBJECT_AGG returns NULL for an index with no
                               -- non-fillfactor options, so FormatJson strips the key and an ordinary index
                               -- extracts byte-identically to before this shipped.
                               (SELECT JSON_OBJECT_AGG(SPLIT_PART(opt, '=', 1), SPLIT_PART(opt, '=', 2))
                                  FROM UNNEST(i.reloptions) AS o(opt)
                                 WHERE opt NOT LIKE 'fillfactor=%') AS "StorageParameters"
                          FROM pg_index idx
                          JOIN pg_class i ON i.oid = idx.indexrelid
                          LEFT JOIN pg_catalog.pg_constraint con ON con.conrelid = idx.indrelid AND con.conname = i.relname AND con.contype IN ('p', 'u', 'x')
                          WHERE idx.indrelid = ('"' || t.table_schema || '"."' || t.table_name || '"')::regclass
                            AND (con.contype IS NULL OR con.contype IN ('p', 'u'))
                          ORDER BY i.relname) sub) AS "Indexes",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT con.conname AS "Name",
                               (SELECT STRING_AGG(a.attname, ',' ORDER BY idx)
                                  FROM pg_attribute a
                                  CROSS JOIN LATERAL UNNEST(con.conkey) WITH ORDINALITY AS u(element, idx)
                                  WHERE a.attrelid = con.conrelid
                                    AND a.attnum = element) AS "Columns",
                               fnsp.nspname AS "RelatedTableSchema",
                               frel.relname AS "RelatedTable",
                               (SELECT STRING_AGG(a.attname, ',' ORDER BY idx)
                                  FROM pg_attribute a
                                  CROSS JOIN LATERAL UNNEST(con.confkey) WITH ORDINALITY AS u(element, idx)
                                  WHERE a.attrelid = frel.oid
                                    AND a.attnum = element) AS "RelatedColumns",
                               '' AS "ShouldApplyExpression",
                               CASE con.confdeltype WHEN 'a' THEN '' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'r' THEN 'RESTRICT' WHEN 'd' THEN 'SET DEFAULT' END AS "DeleteAction",
                               CASE con.confupdtype WHEN 'a' THEN '' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'r' THEN 'RESTRICT' WHEN 'd' THEN 'SET DEFAULT' END AS "UpdateAction",
                               COALESCE(con.condeferrable, FALSE) AS "Deferrable",
                               COALESCE(con.condeferred, FALSE) AS "InitiallyDeferred",
                               CASE con.confmatchtype
                                    WHEN 'f' THEN 'FULL'
                                    WHEN 'p' THEN 'PARTIAL'
                                    WHEN 's' THEN 'SIMPLE'
                                    ELSE 'UNKNOWN'
                                    END AS "MatchType"
                          FROM pg_catalog.pg_constraint con
                          JOIN pg_catalog.pg_class frel ON frel.oid = con.confrelid
                          JOIN pg_catalog.pg_namespace fnsp ON fnsp.oid = frel.relnamespace
                          WHERE con.conrelid = ('"' || t.table_schema || '"."' || t.table_name || '"')::regclass
                            AND con.contype = 'f'
                          ORDER BY con.conname) sub) AS "ForeignKeys",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT con.conname AS "Name",
                               "SchemaSmith"."StripParenWrapping"(SUBSTRING(pg_catalog.PG_GET_CONSTRAINTDEF(con.oid) FROM 6)) AS "Expression",
                               '' AS "ShouldApplyExpression",
                               COALESCE(con.condeferrable, FALSE) AS "Deferrable",
                               COALESCE(con.condeferred, FALSE) AS "InitiallyDeferred"
                        FROM pg_catalog.pg_constraint con
                          WHERE con.conrelid = ('"' || t.table_schema || '"."' || t.table_name || '"')::regclass
                            AND con.contype = 'c'
                          ORDER BY con.conname) sub) AS "CheckConstraints",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT se.stxname AS "Name",
                               COALESCE((SELECT STRING_AGG(CASE k WHEN 'd' THEN 'NDISTINCT' WHEN 'f' THEN 'DEPENDENCIES' WHEN 'm' THEN 'MCV' WHEN 'e' THEN 'EXPRESSIONS' ELSE k::text END, ',')
                                           FROM UNNEST(se.stxkind) AS k), '') AS "Kind",
                               COALESCE(ARRAY_TO_STRING(ARRAY_CAT(COALESCE((SELECT ARRAY_AGG(a.attname::text)
                                                                              FROM UNNEST(se.stxkeys) WITH ORDINALITY AS t(attnum, ord)
                                                                              JOIN pg_attribute a ON a.attrelid = se.stxrelid AND a.attnum = t.attnum
                                                                              WHERE a.attnum > 0),
                                                                           ARRAY[]::text[]),
                                                                  "SchemaSmith"."StatisticsExpressionColumns"(t.table_schema, se.stxname)), ','), '') AS "StatisticsColumns"
                          FROM pg_statistic_ext se
                          WHERE se.stxrelid = ('"' || t.table_schema || '"."' || t.table_name || '"')::regclass
                          ORDER BY se.stxname) sub) AS "Statistics",
               (SELECT JSON_AGG(ROW_TO_JSON(sub))
                  FROM (SELECT i.relname AS "Name",
                               (SELECT am.amname FROM pg_am am WHERE i.relam = am.oid AND i.relkind = 'i') AS "AccessMethod",
                               (SELECT JSON_AGG(ROW_TO_JSON(cols))
                                  FROM (SELECT TRIM(BOTH '"' FROM PG_GET_INDEXDEF(idx.indexrelid, idx::int4, true)) ||
                                                       CASE WHEN (idx.indoption[idx-1] & 1) = 1 THEN ' DESC' || CASE WHEN (idx.indoption[idx-1] & 2) = 2 THEN '' ELSE ' NULLS LAST' END
                                                       ELSE CASE WHEN (idx.indoption[idx-1] & 2) = 2 THEN ' NULLS FIRST' ELSE '' END
                                                       END AS "Column", COALESCE(nsp.nspname || '.' || o.oprname, o.oprname) AS "Operator"
                                          FROM UNNEST(idx.indkey) WITH ORDINALITY AS u(element, idx)
                                          LEFT JOIN LATERAL (SELECT (con.conexclop::oid[])[idx] AS opr_oid) co ON TRUE
                                          LEFT JOIN pg_operator o ON o.oid = co.opr_oid
                                          LEFT JOIN pg_namespace nsp ON nsp.oid = o.oprnamespace AND nsp.nspname != 'pg_catalog'
                                          ORDER BY idx) cols) AS "ExcludeColumns",
                               "SchemaSmith"."StripParenWrapping"(PG_GET_EXPR(idx.indpred, idx.indrelid)) AS "FilterExpression",
                               '' AS "ShouldApplyExpression",
                               COALESCE(con.condeferrable, FALSE) AS "Deferrable",
                               COALESCE(con.condeferred, FALSE) AS "InitiallyDeferred"
                          FROM pg_index idx
                          JOIN pg_class i ON i.oid = idx.indexrelid
                          JOIN pg_catalog.pg_constraint con ON con.conrelid = idx.indrelid AND con.conname = i.relname AND con.contype = 'x'
                          WHERE idx.indrelid = ('"' || t.table_schema || '"."' || t.table_name || '"')::regclass
                          ORDER BY i.relname) sub) AS "ExcludeConstraints",
               -- Row-level security policies (#rls). Emitted only when the table has any, so no existing
               -- package gains an empty "Policies": [] on every table. pg_policies exposes the normalised
               -- USING / WITH CHECK text, which is what a re-deploy compares against.
               (SELECT JSON_AGG(sub ORDER BY sub."Name")
                  FROM (SELECT pol.policyname AS "Name",
                               pol.permissive AS "Permissive",
                               pol.cmd AS "Command",
                               ARRAY_TO_STRING(pol.roles, ',') AS "Roles",
                               COALESCE(pol.qual, '') AS "UsingExpression",
                               COALESCE(pol.with_check, '') AS "WithCheckExpression"
                          FROM pg_policies pol
                          WHERE pol.schemaname = t.table_schema
                            AND pol.tablename = t.table_name) sub) AS "Policies",
               '' AS "ShouldApplyExpression",
               '' AS "OldName",
               rls.relrowsecurity AS "RowLevelSecurity",
               rls.relforcerowsecurity AS "ForceRowLevelSecurity",
               -- Emit the sticky drop-protection marker first-class (only when set true; FormatJson strips the null key
               -- for unprotected tables). Read from the ProductOwnership table-level row by schema+table. #270
               CASE WHEN COALESCE((SELECT po."PreventDrop"
                                     FROM "SchemaSmith"."ProductOwnership" po
                                     WHERE po."Schema" = t.table_schema
                                       AND po."TableName" = t.table_name
                                       AND po."IndexName" IS NULL), FALSE)
                    THEN TRUE END AS "PreventDrop",
               am.amname AS "AccessMethod",
               CASE rls.relpersistence WHEN 'p' THEN 'Logged' WHEN 'u' THEN 'Unlogged' WHEN 't' THEN 'Temporary' END AS "PersistenceType",
               COALESCE((SELECT SPLIT_PART(opt, '=', 2)
                           FROM UNNEST(rls.reloptions) AS opts(opt)
                           WHERE opt LIKE 'fillfactor=%'), '100')::INT2 AS "FillFactor",
               -- 'd' (the default) deliberately yields NULL so FormatJson strips the key: a table that
               -- never touched replica identity extracts exactly as it did before this shipped. #407
               CASE rls.relreplident WHEN 'f' THEN 'FULL' WHEN 'n' THEN 'NOTHING' WHEN 'i' THEN 'INDEX' END AS "ReplicaIdentity",
               CASE WHEN rls.relreplident = 'i'
                    THEN (SELECT ic.relname
                            FROM pg_index ix
                            JOIN pg_class ic ON ic.oid = ix.indexrelid
                           WHERE ix.indrelid = rls.oid
                             AND ix.indisreplident)
                    END AS "ReplicaIdentityIndex",
               -- Same 0-means-default rule as the index block above. Closes the asymmetry with
               -- materialized views, which have carried Tablespace since they shipped.
               (SELECT ts.spcname FROM pg_tablespace ts WHERE ts.oid = rls.reltablespace) AS "Tablespace"
          FROM information_schema.tables t
          JOIN pg_class rls ON rls.relname = t.table_name
                           AND rls.relnamespace IN (SELECT oid FROM pg_namespace WHERE nspname = t.table_schema)
                           AND rls.relkind = 'r'
          JOIN pg_am am ON rls.relam = am.oid
          WHERE t.table_type = 'BASE TABLE'
            AND t.table_schema NOT IN ('pg_catalog', 'information_schema', 'pg_toast', 'SchemaSmith')
            AND p_Schema = t.table_schema
            AND p_Table = t.table_name) tbl;

RETURN result_string;
END $function$