// Copyright (c) SchemaSmith Contributors. Licensed under the SSCL v2.0.

using System;
using Schema.DataAccess;
using Schema.Domain;

namespace SchemaQuench.IntegrationTests.PostgreSQL;

[Category("PostgreSQL")]
[Parallelizable(scope: ParallelScope.All)]
public class TableQuench_IdentityRemovalTests : BaseTableQuenchTests
{
    [Test]
    public void TableQuench_RemovesIdentity_DataPreserving()
    {
        var productName = Guid.NewGuid().ToString();
        var uniqueId = Guid.NewGuid().ToString("N")[..8];
        var schema = "MiscellaneousTests";
        var tableName = $"RemoveIdentity_{uniqueId}";

        using var conn = DbConnectionFactory.ForPlatform(Platform.PostgreSQL).GetDbConnection(_connectionString);
        conn.Open();
        conn.ChangeDatabase(_mainDb);
        using var cmd = conn.CreateCommand();

        cmd.CommandText = $@"
CREATE SCHEMA IF NOT EXISTS ""{schema}"";
CREATE TABLE ""{schema}"".""{tableName}"" (
  ""Id"" INT GENERATED BY DEFAULT AS IDENTITY,
  ""Val"" INT NOT NULL
);
INSERT INTO ""{schema}"".""{tableName}"" (""Id"", ""Val"") OVERRIDING SYSTEM VALUE VALUES (1, 10), (2, 20);";
        cmd.CommandTimeout = 300;
        cmd.ExecuteNonQuery();

        // Confirm identity present
        cmd.CommandText = $@"SELECT a.attidentity FROM pg_attribute a
WHERE a.attrelid = '""{schema}"".""{tableName}""'::regclass AND a.attname = 'Id';";
        Assert.That(cmd.ExecuteScalar()?.ToString(), Is.EqualTo("d"), "Id should be identity before quench");

        var json = $$"""
{
    "Schema": "{{schema}}",
    "Name": "{{tableName}}",
    "Columns": [
        { "Name": "Id",  "DataType": "INT", "Nullable": false },
        { "Name": "Val", "DataType": "INT", "Nullable": false }
    ]
}
""";
        cmd.CommandText = $@"CALL ""SchemaSmith"".""TableQuench""(p_ProductName := '{productName}', p_TableDefinitions := '{json.Replace("'", "''")}', p_WhatIf := false, p_DropTablesRemovedFromProduct := false, p_DropUnknownIndexes := false);";
        cmd.CommandTimeout = 300;
        cmd.ExecuteNonQuery();

        // Identity gone — attidentity is a "char" column; non-identity returns empty char (\0) or ''.
        cmd.CommandText = $@"SELECT a.attidentity FROM pg_attribute a
WHERE a.attrelid = '""{schema}"".""{tableName}""'::regclass AND a.attname = 'Id';";
        var afterIdentity = cmd.ExecuteScalar()?.ToString() ?? "";
        Assert.That(afterIdentity == "" || afterIdentity == "\0", Is.True, $"Id should no longer be identity (got '{afterIdentity}')");
        Assert.That(afterIdentity, Is.Not.EqualTo("d").And.Not.EqualTo("a"), "Id must not be an identity column");

        // Data preserved
        cmd.CommandText = $@"SELECT COUNT(*) FROM ""{schema}"".""{tableName}"";";
        Assert.That(Convert.ToInt32(cmd.ExecuteScalar()), Is.EqualTo(2), "Data must be preserved");

        cmd.CommandText = $@"DROP TABLE ""{schema}"".""{tableName}"";";
        cmd.ExecuteNonQuery();
        conn.Close();
    }
}
