// READ-ONLY reference — generated by `dotnet ef migrations add CreateShop`.
// Recorded in __EFMigrationsHistory as 20240101000000_CreateShop.
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Shop.Migrations;

public partial class CreateShop : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Customer",
            columns: table => new
            {
                CustomerId = table.Column<int>(nullable: false),
                Email = table.Column<string>(maxLength: 256, nullable: false),
                FullName = table.Column<string>(maxLength: 200, nullable: true)
            },
            constraints: table => table.PrimaryKey("PK_Customer", x => x.CustomerId));

        migrationBuilder.CreateTable(
            name: "Product",
            columns: table => new
            {
                ProductId = table.Column<int>(nullable: false),
                Sku = table.Column<string>(type: "varchar(64)", nullable: false),
                Name = table.Column<string>(maxLength: 200, nullable: false),
                UnitPrice = table.Column<decimal>(type: "decimal(10,2)", nullable: false)
            },
            constraints: table => table.PrimaryKey("PK_Product", x => x.ProductId));

        migrationBuilder.CreateTable(
            name: "SalesOrder",
            columns: table => new
            {
                OrderId = table.Column<int>(nullable: false),
                CustomerId = table.Column<int>(nullable: false),
                OrderDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                Status = table.Column<string>(type: "varchar(20)", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_SalesOrder", x => x.OrderId);
                table.ForeignKey("FK_SalesOrder_Customer", x => x.CustomerId,
                    "Customer", "CustomerId");
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("SalesOrder");
        migrationBuilder.DropTable("Product");
        migrationBuilder.DropTable("Customer");
    }
}
