// READ-ONLY reference — generated by `dotnet ef migrations add AddOrderItem`.
// Recorded in __EFMigrationsHistory as 20240115000000_AddOrderItem.
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Shop.Migrations;

public partial class AddOrderItem : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "OrderItem",
            columns: table => new
            {
                OrderItemId = table.Column<int>(nullable: false),
                OrderId = table.Column<int>(nullable: false),
                ProductId = table.Column<int>(nullable: false),
                Quantity = table.Column<int>(nullable: false),
                UnitPrice = table.Column<decimal>(type: "decimal(10,2)", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_OrderItem", x => x.OrderItemId);
                table.ForeignKey("FK_OrderItem_SalesOrder", x => x.OrderId,
                    "SalesOrder", "OrderId");
                table.ForeignKey("FK_OrderItem_Product", x => x.ProductId,
                    "Product", "ProductId");
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("OrderItem");
    }
}
