CREATE OR REPLACE VIEW "pr"."p" AS
 SELECT productid AS id,
    productid,
    name,
    productnumber,
    makeflag,
    finishedgoodsflag,
    color,
    safetystocklevel,
    reorderpoint,
    standardcost,
    listprice,
    size,
    sizeunitmeasurecode,
    weightunitmeasurecode,
    weight,
    daystomanufacture,
    productline,
    class,
    style,
    productsubcategoryid,
    productmodelid,
    sellstartdate,
    sellenddate,
    discontinueddate,
    rowguid,
    modifieddate
   FROM production.product;