DROP FUNCTION IF EXISTS `ufnGetAccountingEndDate`;
DELIMITER //
CREATE FUNCTION `ufnGetAccountingEndDate` ()
  RETURNS datetime
  LANGUAGE SQL
  DETERMINISTIC
  CONTAINS SQL
  SQL SECURITY DEFINER
BEGIN
    RETURN DATE_ADD(CAST('2004-07-01' AS DATETIME), INTERVAL -2000 MICROSECOND);
END //
DELIMITER ;