DROP FUNCTION IF EXISTS `ufnGetAccountingStartDate`;
DELIMITER //
CREATE FUNCTION `ufnGetAccountingStartDate` ()
  RETURNS datetime
  LANGUAGE SQL
  DETERMINISTIC
  CONTAINS SQL
  SQL SECURITY DEFINER
BEGIN
    RETURN CAST('2003-07-01' AS DATETIME);
END //
DELIMITER ;