-- Liquibase's two bookkeeping tables, as Liquibase would have left them.
IF OBJECT_ID('dbo.DATABASECHANGELOG')     IS NOT NULL DROP TABLE dbo.DATABASECHANGELOG;
IF OBJECT_ID('dbo.DATABASECHANGELOGLOCK') IS NOT NULL DROP TABLE dbo.DATABASECHANGELOGLOCK;
CREATE TABLE dbo.DATABASECHANGELOGLOCK (
  ID          INT NOT NULL CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY,
  LOCKED      BIT NOT NULL,
  LOCKGRANTED DATETIME2 NULL,
  LOCKEDBY    NVARCHAR(255) NULL
);
INSERT INTO dbo.DATABASECHANGELOGLOCK (ID,LOCKED) VALUES (1,0);
CREATE TABLE dbo.DATABASECHANGELOG (
  ID            NVARCHAR(255) NOT NULL,
  AUTHOR        NVARCHAR(255) NOT NULL,
  FILENAME      NVARCHAR(255) NOT NULL,
  DATEEXECUTED  DATETIME2 NOT NULL,
  ORDEREXECUTED INT NOT NULL,
  EXECTYPE      NVARCHAR(10) NOT NULL,
  MD5SUM        NVARCHAR(35) NULL,
  DESCRIPTION   NVARCHAR(255) NULL,
  COMMENTS      NVARCHAR(255) NULL,
  TAG           NVARCHAR(255) NULL,
  LIQUIBASE     NVARCHAR(20) NULL,
  CONTEXTS      NVARCHAR(255) NULL,
  LABELS        NVARCHAR(255) NULL,
  DEPLOYMENT_ID NVARCHAR(10) NULL
);
INSERT INTO dbo.DATABASECHANGELOG (ID,AUTHOR,FILENAME,DATEEXECUTED,ORDEREXECUTED,EXECTYPE,DESCRIPTION)
VALUES ('1','dev','db.changelog-master.xml',SYSUTCDATETIME(),1,'EXECUTED','createTable shop'),
       ('2','dev','db.changelog-master.xml',SYSUTCDATETIME(),2,'EXECUTED','addForeignKeyConstraint');
GO
